version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=glints
      - POSTGRES_USER=glints
      - POSTGRES_PASSWORD=glints
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mt-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - GLINTS_POSTGRES__DATABASE_URL=postgresql://glints:glints@postgres:5432/glints